const INCREMENTO = 'INCREMENTO';
const DECREMENTO = 'DECREMENTO';
const INCREMENTO_IMPAR = 'INCREMENTO_IMPAR'
const INCREMENTO_ASINC = 'INCREMENTO_ASINC'

module.exports = {
  INCREMENTO,
  DECREMENTO,
  INCREMENTO_IMPAR,
  INCREMENTO_ASINC
}